on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - run: pip install -r requirements.txt
    - run: pyinstaller datalign/main.spec --distpath /dist --name DatAlign
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v2
      with:
        path: dist/DatAlign.exe