on:
  push:
    tags:
        - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.13
    - name: Installer dependencies
      run: pip install -r requirements.txt

    - name: Run PyInstaller
      run: |
        pyinstaller main.spec
        ren dist/main.exe DatAlign.exe

    - name: Debug ls
      run: ls
      
    - uses: actions/upload-artifact@v2
      with:
        path: dist/DatAlign.exe

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/DatAlign.exe 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release ID
      id: get_release_id
      run: echo "Release ID is ${{ steps.create_release.outputs.id }}"
    
    - name: Debug Release ID
      run: echo ${{ steps.get_release_id.outputs.id }}